apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monica
resources:
  - namespace.yaml
  - backend.yaml
  - agent.yaml
  - frontend.yaml
  - ingress.yaml
images:
  - name: monica-backend
    newTag: latest
  - name: monica-agent
    newTag: latest
  - name: monica-frontend
    newTag: latest

